image: nixos/19.09
packages:
  - nixpkgs.git
  - nixpkgs.cachix
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.09
sources:
  - git@git.sr.ht:~madnat/madkeys
secrets:
  - ce4a1ba6-9c0a-43a7-96c9-e37c85e49742
tasks:
  - build: |
      cd madkeys
      nix-build release.nix
